#ifndef __TURNTABLE_CONF_H__
#define __TURNTABLE_CONF_H__

#define TURNABLE_INIT 0.0f

#define TURNABLE_ID_0_ANGLE 36.0f
#define TURNABLE_ANGLE 36.0f

#define TURNABLE_ID_MAX 5

float turntable_id[TURNABLE_ID_MAX] = {TURNABLE_ID_0_ANGLE,
     TURNABLE_ID_0_ANGLE + TURNABLE_ANGLE*2,
     TURNABLE_ID_0_ANGLE + TURNABLE_ANGLE*4,
     TURNABLE_ID_0_ANGLE + TURNABLE_ANGLE*6,
     TURNABLE_ID_0_ANGLE + TURNABLE_ANGLE*8};

#endif